[tools]
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
selene = "kampfkarren/selene@0.27.1"
rojo = "rojo-rbx/rojo@7.4.3"
luau-lsp = "JohnnyMorganz/luau-lsp@1.32.3"
stylua = "JohnnyMorganz/StyLua@0.20.0"
darklua = "seaofvoices/darklua@0.13.1"
